MODEL_ID = "Lightricks/LTX-Video-0.9.7-distilled"
DEFAULT_RESOLUTION = 512
MAX_DURATION = 10
DEFAULT_FPS = 8

DEFAULT_NUM_INFERENCE_STEPS = 20
DEFAULT_GUIDANCE_SCALE = 7.5
DEFAULT_NUM_FRAMES = 16

ENABLE_CPU_OFFLOAD = True
ENABLE_VAE_SLICING = True
ENABLE_VAE_TILING = True
USE_BFLOAT16 = True

MAX_PROMPT_LENGTH = 500
MAX_CONCURRENT_GENERATIONS = 2
DEFAULT_TIMEOUT = 300

MAX_OUTPUT_FILES = 100
VIDEO_QUALITY = 7
VIDEO_CODEC = "libx264"

LOG_LEVEL = "INFO"
LOG_GPU_MEMORY = True
LOG_GENERATION_STATS = True

# limits to prevent system overload
MAX_GPU_MEMORY_USAGE = 0.9       
MIN_FREE_DISK_SPACE_GB = 10       
MAX_FILE_SIZE_MB = 500            
